#!/usr/bin/env bash
set -euo pipefail
export PYTHONPATH="$HOME/projects/unison:$HOME/projects/unison/src"

cd ~/projects/unison
for p in p7-a2a-v2 p8-flow p9-init; do
  echo "=== $p ==="
  rm -f .unison/state.json reviews/iter-*.md 2>/dev/null
  PYTHONPATH=$PWD:$PWD/src unison run --pipeline $p.yaml 2>&1 || { echo "FAIL: $p"; exit 1; }
  if ! git diff --quiet HEAD -- src/ tests/; then
    git add src/ tests/
    git commit -m "feat($p): auto-generated by Unison pipeline"
  fi
done
echo "P7v2+P8+P9 done"
